[package]
name = "fractal-landscapes-rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_distr="0.4.1"
rand="0.8.4"
linreg="0.2.0"
image="0.23.14"